spring.application.name=Lonjevus

spring.web.resources.static-locations=file:C:/Users/Usuario/Desktop/UCR MEDIACION 2025 PRIMER CICLO/Lenguajes para aplicaciones comerciales/ProyectoLenguajes BACK/proyecto-lonjevus-back/LonjevusBack/uploads/photos/suppliers/
spring.mvc.static-path-pattern=/photos/suppliers/**

spring.servlet.multipart.max-file-size=50MB

