










spring.application.name=Lonjevus
<<<<<<< HEAD

<<<<<<< HEAD
spring.web.resources.static-locations=file:C:/Users/Usuario/Desktop/UCR MEDIACION 2025 PRIMER CICLO/Lenguajes para aplicaciones comerciales/ProyectoLenguajes BACK/proyecto-lonjevus-back/LonjevusBack/uploads/photos/suppliers/
spring.mvc.static-path-pattern=/photos/suppliers/**

spring.servlet.multipart.max-file-size=50MB

=======
spring.servlet.multipart.max-file-size=10MB

spring.servlet.multipart.max-request-size=10MB
>>>>>>> joshua
=======
spring.servlet.multipart.max-file-size=500MB
spring.web.resources.static-locations=file:C:/Users/User/Desktop/Proyecto Lenguajes/proyecto-lonjevus-back/LonjevusBack/uploads/photos/caregiver/
spring.mvc.static-path-pattern=/photos/caregiver/**
>>>>>>> gabriel
