spring.application.name=Lonjevus
#spring.mvc.static-path-pattern=/photos/suppliers/**
spring.servlet.multipart.max-file-size=10MB
spring.web.resources.static-locations=file:C:/Users/JOSHUACALETCESPEDESG/Desktop/Proyecto Lenguajes/proyecto-lonjevus-back/LonjevusBack/uploads/photos/
#spring.mvc.static-path-pattern=/photos/caregiver/**
spring.mvc.static-path-pattern=/photos/**

